Make windows compilation successful
jdah/jdh-8 pull request #4
Opened 2021-06-15 14:05 UTC by Kylogias

NOTE :: This lays the groundwork for windows compilation to be successful but it doesn't ensure that the compiled code will run properly. This PR also cleans up some code to make MinGW-W64 throw less errors and to make time measurements more exact (1024*1024 for megahertz instead of 1000000). Should close #1

2021-06-15 14:11 UTC, Kylogias commented
BUG :: Compilation _**IS**_ successful but when you try to run in the emulator, it silently fails

2021-06-15 14:36 UTC, TheTechRobo requested changes
I suggest putting the Windows build instructions inside the REAdME,along with eeything else.

2021-06-15 15:45 UTC, Kylogias commented
> I suggest putting the Windows build instructions inside the REAdME,along with eeything else.

Done, although I don't know exactly what you mean when you say "everything else"

2021-06-16 18:43 UTC, jdah commented
Wow, nice PR (and thank you for sticking in the style of the existing codebase!) don't have time to merge this in now, but will get to it in the next day or so :)

2021-06-16 19:32 UTC, Kylogias commented
> Wow, nice PR (and thank you for sticking in the style of the existing codebase!) don't have time to merge this in now, but will get to it in the next day or so :)

Thanks, I literally didn't touch the codebase, I only touched the includes. I included stdio.h which iirc wasn't in the original code so you may want to check if it compiles

2021-06-16 19:56 UTC, CoolCat467 commented
Nice!

2021-06-18 17:37 UTC, hdfsyu approved these changes
YES YES YES

2021-06-18 18:27 UTC, jdah commented on emu/emu.c
> +            hz = 1024*1024*100; // 100 MHz (fastest possible)
This is not correct, Hertz are not powers of two, but ten.

2021-06-18 18:31 UTC, jdah commented on Makefile-WIN
> +CCFLAGS=-std=c11 -O0 -g -Wall -Wextra -Wpedantic -Wstrict-aliasing -IC:/cdevlibs/include/ -v
Are `cdevlibs` a universal thing for MinGW? doesn't look like it as far as I can tell.

2021-06-18 18:31 UTC, jdah commented on Makefile-WIN
> +CCFLAGS=-std=c11 -O0 -g -Wall -Wextra -Wpedantic -Wstrict-aliasing -IC:/cdevlibs/include/ -v
Ah, never mind, see in the README update.

2021-06-18 18:38 UTC, Kylogias commented on emu/emu.c
> +            hz = 1024*1024*100; // 100 MHz (fastest possible)
Fixed, although I kept the multiplication to keep it readable

2021-06-18 18:46 UTC, Kylogias commented
I have identified a bug, although I am unsure how to fix it. The bug is that enter doesn't stop the simulation, at least on Windows

2021-06-18 18:53 UTC, jdah commented
This has been merged in with other changes alongside cd6cf42a3e0e333939255c5fdbc5202d122e727e.

2021-06-18 18:53 UTC, closed without merging

2021-06-18 18:53 UTC, jdah commented
If you can fix the enter bug (that's all `poll` is used for btw) please open another PR :)